### ISSUE TITLE
callhorizons fails under Python 3.5 (duh)

### ISSUE THREAD

**Issue by JuanCab** [mommermi/callhorizons#1]
Is it possible call horizons is not compatible with Python 3.5?  I have a script that works fine under Python 2.7, but when I try to use it under Python 3.5 I get a reproducible error.  I'd appreciate clarification on whether CALLHORIZONS 1.0.1 is Python 3.5 compatible.

I can reproduce the error in ipython as follows:
$ python --version
Python 3.5.1 :: Anaconda custom (x86_64)
$ ipython --version
5.1.0
$ ipython
In [1]: import callhorizons
## In [2]: eros = callhorizons.query('Eros')

AttributeError                            Traceback (most recent call last)
<ipython-input-2-a158225862d2> in <module>()
----> 1 eros = callhorizons.query('Eros')

AttributeError: module 'callhorizons' has no attribute 'query'

**Comment by JuanCab** [comment]
This comes under the category of RTFM... didn't find the mention that it was only Python 2.7 compatible in the documentation, because, you know, it was only on the main page for the documentation.  My error, sorry.

**Comment by mommermi** [comment]
Hi Juan,

no worries! But it's a good idea to make it compatible to Python 3.5 (I admit that I never thought about this...)
Let me reopen this issue and I'll put it on my list for next week.

Michael

**Comment by mommermi** [comment]
@JuanCab callhorizons should now work with Python 3.5! Give it a try and let me know if it works for you. M
